version: "3.4"

services:
  backend_api:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    environment:
      ENV: "docker"
      PORT: "8000"
      WORKERS: "1"
    ports:
      - "8000:8000"

  telegram_bot:
    build:
      dockerfile: Dockerfile
      context: ./telegram_bot
    environment:
      TELEGRAM_TOKEN: ""
      BACKEND_API_URL: "http://backend_api:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

