version: "3.4"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      ENV: "docker"
      PORT: "8000"
      WORKERS: "1"
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

